---
- include: "{{ansible_os_family}}.yml"

- name: pip install or upgrade
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - python-openstackclient
    - python-heatclient
    - keystoneauth-oidc-authz-code

- name: upgrade keystone client to the latest in github
  pip: name="git+https://github.com/openstack/python-keystoneclient.git" editable=false
