---
- include: "{{ansible_os_family}}.yml"

- name: pip install or upgrade
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - python-openstackclient
    - python-heatclient
    - "git+https://github.com/openstack/python-keystoneclient.git"
    - keystoneauth-oidc-authz-code
