---
- include: "{{ansible_os_family}}.yml"

- name: upgrade pip
  pip: name=pip state=latest

- name: pip install openstack client
  pip: name=python-openstackclient state=latest

- name: upgrade keystone client to the latest in github
  pip: name="git+https://github.com/openstack/python-keystoneclient.git" editable=false
